# Generated by Django 3.0.3 on 2020-02-12 19:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask42app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_jsonb',
            name='some_element',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
